### PR TITLE
#3: Support Java9

### PR DESCRIPTION
**Pull request by xerial**

### CODE REVIEW

**Comment by xerial** [comment]
Stuck with this error in Java9:
```
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /home/travis/.sbt/boot/scala-2.10.6/lib/scala-library.jar(scala/package.class)
```

**Comment by xuwei-k** [comment]
- https://github.com/xuwei-k/sbt-jcheckstyle/commit/21c5a45b53100aa3e32a4a748a5e1c4f2eb82c1d
- https://travis-ci.org/xuwei-k/sbt-jcheckstyle/builds/231800768

**Comment by xerial** [comment]
@xuwei-k Thanks. Could you send the above commit as another PR?

**Comment by xerial** [comment]
Closed in favor of #5

**Pull request closed without merging**
